# recommended profile includes all checked rules from this page: http://eslint.org/docs/rules
extends: 'eslint:recommended'

env:
  es6: true
  node: true

rules:
  # Possible Errors
  no-extra-parens: error
  # no-prototype-builtins: error
  no-unsafe-finally: error
  valid-jsdoc: [warn, requireReturn: false]

  # Best Practices
  block-scoped-var: error
  consistent-return: error
  curly: [error, multi-line, consistent]
  default-case: error
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, allow-null]
  no-alert: error
  no-caller: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-invalid-this: error
  no-implied-eval: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-native-reassign: error
  no-new: error
  no-new-wrappers: error
  no-param-reassign: error
  no-proto: error
  no-return-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-warning-comments: [warn, {location: anywhere, terms: [TODO, TODOC, FIXME]}]
  no-with: error
  radix: error

  # Variables
  no-catch-shadow: error
  no-shadow: error
  no-undefined: error

  # Node.js and CommonJS
  callback-return: error
  handle-callback-err: error
  no-mixed-requires: error
  no-path-concat: error

  # stylistic
  array-bracket-spacing: [error, never]
  block-spacing: [error, always]
  brace-style: [error, 1tbs]
  camelcase: error
  comma-spacing: error
  comma-style: [error, last]
  computed-property-spacing: [error, never]
  eol-last: error
  indent: [error, 2]
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  max-len: [error, 120]
  new-cap: error
  new-parens: error
  no-array-constructor: error
  no-bitwise: error
  no-lonely-if: error
  no-mixed-spaces-and-tabs: error
  no-new-object: error
  no-spaced-func: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing: error
  operator-linebreak: [error, before]
  quote-props: [error, as-needed]
  quotes: [error, single]
  semi: [error, never]
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: error
  space-unary-ops: error
  spaced-comment: error

  # ECMAScript 6
  arrow-body-style: [error, as-needed]
  arrow-parens: [error, as-needed]
  arrow-spacing: error
  no-class-assign: error
  no-confusing-arrow: [error, allowParens: true]
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  # spread-spacing: [error, never]
  template-curly-spacing: [error, never]